[theme]
base = "light"
primaryColor = "#29d982"
backgroundColor = "#f6f8f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#111411"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
