[theme]
base = "light"
primaryColor = "#2864F0"
backgroundColor = "#F8F7F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#23221E"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
